services:
  api:
    build: ./api
    container_name: zapsign_backend
    command: gunicorn src.zapsign_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  ai_service:
    build: ./ai_service
    container_name: zapsign_ai_service
    volumes:
      - ./ai_service:/app
    env_file:
      - .env
    depends_on:
      - redis
      - neo4j

  postgres:
    image: postgres:15
    container_name: zapsign_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: zapsign_redis
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:5
    container_name: zapsign_neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD} # Senha via .env
      - NEO4J_PLUGINS=["apoc"]

volumes:
  postgres_data:
  neo4j_data: