
name: Create and Publish Backend Docker Image

on:
  workflow_dispatch: # Permite acionamento manual pela interface do GitHub Actions

jobs:
  build_and_push_backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: . # O contexto é a raiz do repositório atual
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/zapsign-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: backend-release-${{ github.run_number }}
          body: |
            New release for the Backend service.
            - Docker Image: `ghcr.io/${{ github.repository_owner }}/zapsign-backend:latest`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
